server:
  port: 6001

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /cloud  #统一访问前缀
  routes:
    web-server1.serviceId:
      web-server1
    web-server1.path:
      /conl/**
    web-server2.serviceId:
      web-server2
    web-server2.path:
      /like2/**
    web-server3.serviceId:
      web-server3
    web-server3.path:
      /doctor/**
    web-server4.serviceId:
      web-server3
    web-server4.path:
      /patient/**


  ignored-patterns: /cloud/conl/test/user/validate   #不允许访问


#  ratelimit:
#    enabled: true
#    default-policy-list:
#    -  limit: 10
#       quota: 1
#       refresh-interval: 5
#       type:
#         - origin
#    repository: redis

  ratelimit:
    enabled: true
    policies:
      web-server1:
        limit: 10
        refresh-interval: 1
        type: origin


nofilter:
  url: /cloud/conl/test/user/noValidate

#动态刷新
management:
  endpoints:
    web:
      exposure:
        include: refresh,health



