server:
  port: 7007
spring:
  application:
    name: spring-cloud-gateway-predicate

  cloud:
    gateway:
      routes:
      - id: web-server1
        uri: lb://web-server1
        predicates:
        - After=2020-01-01T16:53:45.933+08:00[Asia/Shanghai]
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway:
      debug
