server:
  port: 8082

spring:
  application:
    name: sc-gateway-limit-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: web-server1
        uri: lb://web-server1
        predicates:
          - Path=/myweb/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 9
            key-resolver: '#{@ipKeyResolver}'
  redis:
    host: 127.0.0.1
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
